### ISSUE TITLE
TODO ui 6

### ISSUE THREAD

**Issue by jmfrancois** [Talend/ui-scripts#131]
* [ ] custom build umd
* [ ] post install script
* [ ] merge manifest for initiator
* [ ] upgrade script
